//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collectreq
    {
        public int collectid { get; set; }
        public string restname { get; set; }
        public string food_name { get; set; }
        public string time { get; set; }
        public string location { get; set; }
        public Nullable<int> empid { get; set; }
        public string status { get; set; }
    
        public virtual emp emp { get; set; }
    }
}
