//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public emp()
        {
            this.collectreqs = new HashSet<collectreq>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<collectreq> collectreqs { get; set; }
    }
}
